# Generated by Django 6.1.1 on 2026-09-22 04:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'label_definitions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('language', models.CharField(default='vi', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=32)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ANNOTATOR', 'Annotator')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
        migrations.CreateModel(
            name='SegmentAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segment_annotations',
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(max_length=32)),
                ('youtube_url', models.CharField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('source_status', models.CharField(choices=[('PENDING_METADATA', 'Pending metadata'), ('READY', 'Ready'), ('METADATA_FAILED', 'Metadata failed')], default='PENDING_METADATA', max_length=32)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video_sources',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('login_identifier', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=32)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE'])), name='ck_users_status')],
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_index', models.IntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('transcript', models.CharField(blank=True, max_length=10000, null=True)),
                ('definition_revision', models.IntegerField(default=1)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processing.processingartifact')),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processing.processingjob')),
            ],
            options={
                'db_table': 'audio_segments',
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='workspace.project')),
                ('output_format', models.CharField(default='WAV', max_length=16)),
                ('encoding', models.CharField(default='PCM', max_length=16)),
                ('sample_rate_hz', models.IntegerField(default=16000)),
                ('channels', models.IntegerField(default=1)),
                ('loudness_normalization', models.BooleanField(default=False)),
                ('naming_convention', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'ARCHIVED'])), name='ck_projects_status'),
        ),
        migrations.AddField(
            model_name='labeldefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.appuser'),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='annotations', to='workspace.appuser'),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='workspace.labeldefinition'),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='removed_annotations', to='workspace.appuser'),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='workspace.audiosegment'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workspace.videosource'),
        ),
        migrations.AddConstraint(
            model_name='labeldefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), name='uq_label_proj_name_lower'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['user'], name='ix_pm_user_id'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project'], name='ix_pm_project_id'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['project', 'user'], name='ix_pm_active'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uq_pm_project_user'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['OWNER', 'ANNOTATOR'])), name='ck_pm_role'),
        ),
        migrations.AddIndex(
            model_name='segmentannotation',
            index=models.Index(fields=['segment'], name='ix_sa_segment_id'),
        ),
        migrations.AddIndex(
            model_name='segmentannotation',
            index=models.Index(fields=['annotator'], name='ix_sa_annotator_id'),
        ),
        migrations.AddConstraint(
            model_name='segmentannotation',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('segment', 'label', 'annotator'), name='uq_sa_active'),
        ),
        migrations.AddConstraint(
            model_name='videosource',
            constraint=models.UniqueConstraint(fields=('project', 'youtube_video_id'), name='uq_vs_project_video'),
        ),
        migrations.AddConstraint(
            model_name='videosource',
            constraint=models.CheckConstraint(condition=models.Q(('source_status__in', ['PENDING_METADATA', 'READY', 'METADATA_FAILED'])), name='ck_vs_source_status'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.UniqueConstraint(fields=('source', 'segment_index'), name='uq_as_source_index'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_seconds__gte', 0)), name='ck_as_start_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_seconds__gt', models.F('start_seconds'))), name='ck_as_end_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.CheckConstraint(condition=models.Q(('definition_revision__gte', 1)), name='ck_as_revision_min'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.CheckConstraint(condition=models.Q(('processing_status__in', ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'])), name='ck_as_proc_status'),
        ),
    ]
