# Generated by Django 6.1.1 on 2026-09-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_asr_runs'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='current_asr_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processing.processingjob'),
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='current_asr_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processing.asrrun'),
        ),
    ]
