# Generated by Django 6.1.1 on 2026-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_asr_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
