# Generated by Django 6.1.1 on 2026-09-24 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_annotahub_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment_group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignment_batches_created', to='workspace.appuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_batches', to='workspace.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_batches', to='workspace.videosource')),
            ],
            options={
                'db_table': 'assignment_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], db_index=True, default='ASSIGNED', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments_created', to='workspace.appuser')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='annotation_assignments', to='workspace.appuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspace.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspace.audiosegment')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='workspace.assignmentbatch')),
            ],
            options={
                'db_table': 'annotation_assignments',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='ix_aa_project_status'), models.Index(fields=['assignee', 'status'], name='ix_aa_assignee_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'IN_PROGRESS'])), fields=('segment', 'assignee', 'assignment_group_id'), name='uq_aa_active_segment_assignee_group'), models.CheckConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'RELEASED'])), name='ck_aa_status')],
            },
        ),
    ]
