# Generated by Django 6.1.1 on 2026-09-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_work_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='audio_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='audio_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_audio_reviewed', to='workspace.appuser'),
        ),
        migrations.AddField(
            model_name='label',
            name='exclude_guidance',
            field=models.TextField(blank=True, help_text='Operational definition: what to exclude for this label.', null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='include_guidance',
            field=models.TextField(blank=True, help_text='Operational definition: what to include for this label.', null=True),
        ),
        migrations.AddField(
            model_name='projectlabel',
            name='override_exclude_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectlabel',
            name='override_include_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='require_annotation',
            field=models.BooleanField(default=True, help_text='Export readiness requires at least one active annotation.'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='require_audio_review',
            field=models.BooleanField(default=True, help_text='Export readiness requires OWNER Audio OK review.'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='require_transcript',
            field=models.BooleanField(default=True, help_text='Export readiness requires a non-empty canonical transcript.'),
        ),
    ]
