# Generated by Django 6.1.1 on 2026-09-22 04:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=16)),
                ('route', models.CharField(max_length=512)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=32)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.CreateModel(
            name='ProcessingArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=512)),
                ('format', models.CharField(max_length=16)),
                ('sample_rate_hz', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('file_size_bytes', models.IntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processing_artifacts',
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_revision', models.IntegerField()),
                ('job_type', models.CharField(choices=[('EXTRACT_SEGMENT_AUDIO', 'Extract segment audio')], default='EXTRACT_SEGMENT_AUDIO', max_length=64)),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('config_snapshot', models.JSONField()),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('STALE', 'Stale'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=32)),
                ('attempt_n', models.IntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.CharField(blank=True, max_length=2000, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processing_jobs',
            },
        ),
        migrations.CreateModel(
            name='SourceMediaCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=512)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_media_cache',
            },
        ),
    ]
