# Generated by Django 6.1.1 on 2026-09-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='workspace.appuser'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='processing.processingjob'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workspace.audiosegment'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workspace.videosource'),
        ),
        migrations.AddField(
            model_name='processingartifact',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='processing.processingjob'),
        ),
        migrations.AddField(
            model_name='sourcemediacache',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_cache', to='workspace.videosource'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['created_at'], name='ix_idem_created_at'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('actor_user', 'method', 'route', 'key'), name='uq_idem_scope'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['segment'], name='ix_pj_segment_id'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['project'], name='ix_pj_project_id'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status'], name='ix_pj_status'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'STALE', 'CANCELLED'])), name='ck_processing_jobs_status'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('job_type__in', ['EXTRACT_SEGMENT_AUDIO'])), name='ck_processing_jobs_job_type'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('segment', 'expected_revision'), name='uq_pj_active'),
        ),
    ]
