# Generated by Django 6.1.1 on 2026-09-23 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsrRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_revision', models.IntegerField()),
                ('artifact_checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('provider', models.CharField(default='local', max_length=32)),
                ('engine', models.CharField(default='fake', max_length=64)),
                ('model', models.CharField(default='base', max_length=128)),
                ('model_name', models.CharField(max_length=64)),
                ('model_size', models.CharField(max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=64, null=True)),
                ('model_path_or_id', models.CharField(blank=True, max_length=512, null=True)),
                ('language_requested', models.CharField(max_length=16)),
                ('language_detected', models.CharField(blank=True, max_length=16, null=True)),
                ('task', models.CharField(default='transcribe', max_length=32)),
                ('device', models.CharField(blank=True, max_length=16, null=True)),
                ('compute_type', models.CharField(blank=True, max_length=32, null=True)),
                ('decode_params', models.JSONField(default=dict)),
                ('text', models.TextField()),
                ('segments_json', models.JSONField(blank=True, null=True)),
                ('words_json', models.JSONField(blank=True, null=True)),
                ('confidence_summary', models.JSONField(blank=True, null=True)),
                ('is_stale_result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'asr_runs',
            },
        ),
        migrations.RemoveConstraint(
            model_name='processingjob',
            name='ck_processing_jobs_job_type',
        ),
        migrations.RemoveConstraint(
            model_name='processingjob',
            name='uq_pj_active',
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('EXTRACT_SEGMENT_AUDIO', 'Extract segment audio'), ('TRANSCRIBE_SEGMENT_AUDIO', 'Transcribe segment audio')], default='EXTRACT_SEGMENT_AUDIO', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('job_type__in', ['EXTRACT_SEGMENT_AUDIO', 'TRANSCRIBE_SEGMENT_AUDIO'])), name='ck_processing_jobs_job_type'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('segment', 'expected_revision', 'job_type'), name='uq_pj_active'),
        ),
        migrations.AddField(
            model_name='asrrun',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asr_runs', to='processing.processingartifact'),
        ),
        migrations.AddField(
            model_name='asrrun',
            name='processing_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='asr_run', to='processing.processingjob'),
        ),
        migrations.AddField(
            model_name='asrrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asr_runs', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='asrrun',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asr_runs', to='workspace.audiosegment'),
        ),
        migrations.AddField(
            model_name='asrrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asr_runs', to='workspace.videosource'),
        ),
        migrations.AddIndex(
            model_name='asrrun',
            index=models.Index(fields=['segment', 'created_at'], name='ix_asr_runs_seg_created'),
        ),
        migrations.AddIndex(
            model_name='asrrun',
            index=models.Index(fields=['project', 'created_at'], name='ix_asr_runs_proj_created'),
        ),
        migrations.AddIndex(
            model_name='asrrun',
            index=models.Index(fields=['artifact'], name='ix_asr_runs_artifact_id'),
        ),
    ]
