# Generated by Django 6.1.1 on 2026-09-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_asr_runs'),
        ('workspace', '0002_asr_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsrPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asr_preferences', serialize=False, to='workspace.appuser')),
                ('use_system_defaults', models.BooleanField(default=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('local_model', models.CharField(blank=True, max_length=128, null=True)),
                ('local_device', models.CharField(blank=True, max_length=16, null=True)),
                ('local_compute_type', models.CharField(blank=True, max_length=32, null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('openai_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_asr_preferences',
            },
        ),
        migrations.CreateModel(
            name='SystemAsrSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('local_model', models.CharField(blank=True, max_length=128, null=True)),
                ('local_device', models.CharField(blank=True, max_length=16, null=True)),
                ('local_compute_type', models.CharField(blank=True, max_length=32, null=True)),
                ('openai_enabled', models.BooleanField(blank=True, null=True)),
                ('openai_default_model', models.CharField(blank=True, max_length=128, null=True)),
                ('openai_base_url', models.CharField(blank=True, max_length=512, null=True)),
                ('openai_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspace.appuser')),
            ],
            options={
                'db_table': 'system_asr_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_system_asr_settings_singleton')],
            },
        ),
    ]
