# Generated by Django 6.1.1 on 2026-09-24 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_asr_prefs_w7'),
        ('workspace', '0002_asr_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_preferences', serialize=False, to='workspace.appuser')),
                ('use_system_defaults', models.BooleanField(default=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('ollama_base_url', models.CharField(blank=True, max_length=512, null=True)),
                ('ollama_model', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_ai_preferences',
            },
        ),
        migrations.CreateModel(
            name='AiAssistRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('segment_revision', models.IntegerField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ai_assist_runs', to='workspace.appuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assist_runs', to='workspace.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assist_runs', to='workspace.audiosegment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assist_runs', to='workspace.videosource')),
            ],
            options={
                'db_table': 'ai_assist_runs',
                'indexes': [models.Index(fields=['segment', 'created_at'], name='ix_ai_assist_runs_seg_created')],
            },
        ),
        migrations.CreateModel(
            name='SystemAiSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('ollama_base_url', models.CharField(blank=True, max_length=512, null=True)),
                ('ollama_default_model', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspace.appuser')),
            ],
            options={
                'db_table': 'system_ai_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_system_ai_settings_singleton')],
            },
        ),
    ]
